### ISSUE TITLE
Some responsive issues

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/fastUI#10]
Hey,
very cool project and so many useful components.

I'll try some of them tommorow for a new project, thank you.

While checking them out on mobile (OnePlus Nord with Chrome) I noticed some responsive issues with the examples.

Best,
Tom
![Screenshot_20201229-223854](https://user-images.githubusercontent.com/987947/103315822-056ad700-4a27-11eb-9d49-fddc4ed183e2.jpg)
![Screenshot_20201229-223958](https://user-images.githubusercontent.com/987947/103315826-069c0400-4a27-11eb-8b59-92bfc6dd37b7.jpg)
![Screenshot_20201229-224027](https://user-images.githubusercontent.com/987947/103315828-069c0400-4a27-11eb-84b0-7125a2b34a4e.jpg)
![Screenshot_20201229-224053](https://user-images.githubusercontent.com/987947/103315829-07349a80-4a27-11eb-9d28-58b3c1bfa5b4.jpg)

**Comment by SlaraMk** [comment]
Hi , I have an issue with chart.js 
Call to undefined method App\Charts\BloodPresser::labels()

**Comment by ciruz** [comment]
> Hi , I have an issue with chart.js 
> Call to undefined method App\Charts\BloodPresser::labels()

    Hey, wrong issue?

**Comment by Charlie85270** [comment]
Fixed with commit : https://github.com/Charlie85270/fastUI/commit/ccb9d43ed14d5a66ac6a645f31ff47d5ccd7d9ec
