### ISSUE TITLE
Live Editor

### ISSUE THREAD

**Issue by imrandyk** [Charlie85270/fastUI#9]
PostCSS is removing unused classes from the finalized css file so this is causing the live editor to not work as I would expect. This could be fixed with your tailwind config and not purge anything.

Example: On the Button change the bg-indigo-600 to bg-indigo-700 and it becomes transparent.

![image](https://user-images.githubusercontent.com/799499/103312836-daab5f00-49e3-11eb-8672-6f198b60a721.png)

**Comment by Charlie85270** [comment]
Hi imrandyk, 

Thanks for the issue. 
For better performance I have configured purgeCSS to remove all unused tailwind classes. 
Without this purge, the development build of Tailwind CSS is 3020.7kB minified , it's too large. 
Performance is for me an important thing, this is why I choose NextJS to build the site statickly.  
The goal of Tailwind-kit isn't to be a "copeden" like. I develop the live code edition like a "bonus" but I can understand that could be frustrated that the render isn't "normal". 

I will mention this on configuration page to prevent all users.

Thanks you
